### ISSUE TITLE
Incorrectly detecting HTTPS

### ISSUE THREAD

**Issue by h3retic** [sAjibuu/upload_bypass_carnage#12] opened 2024-02-28 00:43 UTC
For some reason it is targeting HTTPS url with the below form, how is it detecting HTTP or HTTPS? The origin and referer both specify http:

```
POST /upload.php HTTP/1.1
Host: 192.168.172.171
Content-Length: 16408
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
Origin: http://192.168.172.171
Content-Type: multipart/form-data; boundary=----WebKitFormBoundarykzXfPCHHOtGYXT6m
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.6167.85 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Referer: http://192.168.172.171/upload.html
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: close

------WebKitFormBoundarykzXfPCHHOtGYXT6m
Content-Disposition: form-data; name="fileToUpload"; filename="*filename*"
Content-Type: *mimetype*

*data*
-----WebKitFormBoundarykzXfPCHHOtGYXT6m-
Content-Disposition: form-data; name="submit"

Upload
------WebKitFormBoundarykzXfPCHHOtGYXT6m--
```

**Comment by sAjibuu** [comment] 2024-02-28 06:57
Yes, you are correct.
Right now, the HTTP/s protocol is hardcoded in the config.py under the lib directory.
You can change there the protocol you need.
I'm having some hard time detecting the correct protocol, but I'll fix this soon and make the program change it automatically. 
Btw, do you remember if you use the --burp flag?

**Comment by sAjibuu** [comment] 2024-03-01 15:45
The issue is now fixed.

**Closed as completed** 2024-03-01 15:46 UTC

**Comment by 0xNoport** [comment] 2024-07-19 15:39
the issue is not fixed, i have the same issue
